# Generated by Django 4.2.30 on 2026-09-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accommodation_rent_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='bathroom_type',
            field=models.CharField(blank=True, choices=[('en_suite', 'En-suite'), ('shared', 'Shared bathroom')], max_length=20, null=True),
        ),
    ]
