# Generated by Django 4.2.30 on 2026-09-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accommodation_bathroom_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='accommodation_type',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='bathroom_type',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='offers_catered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='offers_en_suite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='offers_self_catered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='offers_shared_bathroom',
            field=models.BooleanField(default=False),
        ),
    ]
