# Generated by Django 4.2.30 on 2026-09-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_city_accommodation_latitude_accommodation_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gym',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='gym',
            name='monthly_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
