# Generated by Django 4.2.30 on 2026-09-14 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_gym_options_gym_monthly_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLoanBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_situation', models.CharField(choices=[('at_home', 'Living with parents/guardians'), ('away_outside_london', 'Away from home, outside London'), ('away_in_london', 'Away from home, in London')], max_length=30, unique=True)),
                ('max_loan', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_loan', models.DecimalField(decimal_places=2, max_digits=8)),
                ('income_threshold', models.DecimalField(decimal_places=2, max_digits=8)),
                ('taper_divisor', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catering', models.CharField(max_length=20)),
                ('bathroom', models.CharField(max_length=20)),
                ('gym_membership', models.CharField(max_length=3)),
                ('walking_distance', models.CharField(max_length=20)),
                ('nights_out_per_week', models.PositiveSmallIntegerField()),
                ('night_out_budget', models.CharField(max_length=20)),
                ('other_subscriptions_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('lifestyle_preference', models.CharField(blank=True, max_length=20)),
                ('household_income', models.DecimalField(decimal_places=2, max_digits=9)),
                ('living_situation', models.CharField(max_length=30)),
                ('year_of_study', models.CharField(max_length=20)),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('part_time_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('scholarship_amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accommodation')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trials', models.PositiveIntegerField()),
                ('weekly_cost_results', models.JSONField()),
                ('median_cost_per_week', models.DecimalField(decimal_places=2, max_digits=8)),
                ('p10_cost_per_week', models.DecimalField(decimal_places=2, max_digits=8)),
                ('p90_cost_per_week', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mean_cost_per_week', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stdev_cost_per_week', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weekly_income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_run', to='core.report')),
            ],
        ),
    ]
