# Generated by Django 4.2.30 on 2026-09-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_maintenanceloanband_report_simulationrun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='rent_per_week',
            new_name='rent_catered_ensuite',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='rent_catered_shared',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='rent_self_catered_ensuite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='rent_self_catered_shared',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
