# Generated by Django 4.2.30 on 2026-09-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_rent_per_week_accommodation_rent_catered_ensuite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='household_income',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
