# Generated by Django 4.2.30 on 2026-09-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_report_household_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='spend_savings',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
