# Generated by Django 4.2.30 on 2026-09-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_report_spend_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='loan_spread',
            field=models.CharField(default='term_time', max_length=10),
        ),
    ]
