# Generated by Django 4.2.30 on 2026-09-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_report_loan_spread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='lifestyle_preference',
        ),
    ]
